# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BayCli < Formula
  desc "CLI tool to interact with the Bay container platform"
  homepage "https://github.com/dpc-sdp/bay-cli"
  version "1.4.3"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/dpc-sdp/bay-cli/releases/download/v1.4.3/bay_darwin_amd64.tar.gz"
      sha256 "ddda22a6bc7dfaf7d7dd1d43771d940b29c6ccba833f13b7912c9739b6e8ebdd"

      def install
        bin.install "bay"
      end
    end
    on_arm do
      url "https://github.com/dpc-sdp/bay-cli/releases/download/v1.4.3/bay_darwin_arm64.tar.gz"
      sha256 "e4b3c3e3268179dcab0cc05e68e34b7dc0918b7980e362faac7efd74a9f718cf"

      def install
        bin.install "bay"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dpc-sdp/bay-cli/releases/download/v1.4.3/bay_linux_amd64.tar.gz"
        sha256 "76b16386163e2c7f86c1903db355e24e5cedcec54c5d229b9c820babb7c40585"

        def install
          bin.install "bay"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dpc-sdp/bay-cli/releases/download/v1.4.3/bay_linux_arm64.tar.gz"
        sha256 "eebc81ca4d7c528a603725b7d530e02c99aecbf146b2637ed1cf54664acdde05"

        def install
          bin.install "bay"
        end
      end
    end
  end
end
