# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BayCli < Formula
  desc "CLI tool to interact with the Bay container platform"
  homepage "https://github.com/dpc-sdp/bay-cli"
  version "1.1.5"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/dpc-sdp/bay-cli/releases/download/v1.1.5/bay_darwin_amd64.tar.gz"
      sha256 "4a37400d7c203b41d0b449e7f866724ec3e7477d64efce3d9bd29e85a3dce8d6"

      def install
        bin.install "bay"
      end
    end
    on_arm do
      url "https://github.com/dpc-sdp/bay-cli/releases/download/v1.1.5/bay_darwin_arm64.tar.gz"
      sha256 "d038cf530836c82b36a79483b466158363c1e6a74f76dee7c940cf792c30fe96"

      def install
        bin.install "bay"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dpc-sdp/bay-cli/releases/download/v1.1.5/bay_linux_amd64.tar.gz"
        sha256 "4dfef89297103c02e473fcca4c0c757050eb5a35c2fcd846687aaf714a302fce"

        def install
          bin.install "bay"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dpc-sdp/bay-cli/releases/download/v1.1.5/bay_linux_arm64.tar.gz"
        sha256 "c6809c1d5abb4dadba23bea7f3ac1a94c0f4023546c90d74cf3313296936742e"

        def install
          bin.install "bay"
        end
      end
    end
  end
end
