# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bay < Formula
  desc "CLI for the Bay Hosting Platform"
  homepage "https://github.com/dpc-sdp/bay-cli"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/dpc-sdp/bay-cli/releases/download/v0.0.2/bay_darwin_arm64.tar.gz"
      sha256 "5adc6d466c0e33d60e446c750992e969822ec9deffd4d4f7f9d7a70accaf31ae"

      def install
        bin.install "bay"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dpc-sdp/bay-cli/releases/download/v0.0.2/bay_darwin_amd64.tar.gz"
      sha256 "a30f69f96b8b4138902b79e93399a8cb7eaecb0a246c42a1cd2b0e33f1498773"

      ddef install
        bin.install "bay"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dpc-sdp/bay-cli/releases/download/v0.0.2/bay_linux_arm64.tar.gz"
      sha256 "81465c496348c4c760804b566da9b92263f52a4247e4f1d2f8e84e782c7c9f57"

      ddef install
        bin.install "bay"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dpc-sdp/bay-cli/releases/download/v0.0.2/bay_linux_amd64.tar.gz"
      sha256 "62fed7728187e4ea4ead56f9992dca3148e8966b5044205aedd7a764983fcfd4"

      ddef install
        bin.install "bay"
      end
    end
  end
end
