# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BayCli < Formula
  desc "CLI tool to interact with the Bay container platform"
  homepage "https://github.com/dpc-sdp/bay-cli"
  version "0.0.4-alpha5"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/dpc-sdp/bay-cli/releases/download/v0.0.4-alpha5/bay-cli_Darwin_arm64.tar.gz"
      sha256 "b24abae52767bd3d45582091a6932471350e135b52125d7900c29817bf00675e"

      def install
        bin.install "bay"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dpc-sdp/bay-cli/releases/download/v0.0.4-alpha5/bay-cli_Darwin_x86_64.tar.gz"
      sha256 "e74b27c7c647e51d8e6227e24483c0e184b007ad77d39e2485c7382c4074bec4"

      def install
        bin.install "bay"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dpc-sdp/bay-cli/releases/download/v0.0.4-alpha5/bay-cli_Linux_arm64.tar.gz"
      sha256 "dbfb7777ac108c4323d06503355b7ba708d7027c7ac7d411ddb53c2c7973cbda"

      def install
        bin.install "bay"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dpc-sdp/bay-cli/releases/download/v0.0.4-alpha5/bay-cli_Linux_x86_64.tar.gz"
      sha256 "e4715c5ef665c7035f9d6fea7edfbe31329021cb1bff53f6d9a7885c47baca66"

      def install
        bin.install "bay"
      end
    end
  end
end
