# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BayCli < Formula
  desc "CLI tool to interact with the Bay container platform"
  homepage "https://github.com/dpc-sdp/bay-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dpc-sdp/homebrew-bay-cli/releases/download/v0.1.0/homebrew-bay-cli_Darwin_x86_64.tar.gz"
      sha256 "bc65d37c393e3df8e01385451267e2c31d200b6f3b4f011b6286c24a30fd518f"

      def install
        bin.install "bay"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dpc-sdp/homebrew-bay-cli/releases/download/v0.1.0/homebrew-bay-cli_Darwin_arm64.tar.gz"
      sha256 "b283b016e345c993069f4b50ab2b9a213469ab35f1e42dca19895ca31935c0d6"

      def install
        bin.install "bay"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dpc-sdp/homebrew-bay-cli/releases/download/v0.1.0/homebrew-bay-cli_Linux_arm64.tar.gz"
      sha256 "42f115e489d38ff35b22ec0462c19ec89b163fab187a1ef46622872e49da4caf"

      def install
        bin.install "bay"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dpc-sdp/homebrew-bay-cli/releases/download/v0.1.0/homebrew-bay-cli_Linux_x86_64.tar.gz"
      sha256 "ac4854954c04fa7ad548ce976b046136e09f1187d55c20768d27d91265ccca5f"

      def install
        bin.install "bay"
      end
    end
  end

  def caveats
    <<~EOS
      How to use this binary
    EOS
  end
end
