# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BayCli < Formula
  desc "CLI tool to interact with the Bay container platform"
  homepage "https://github.com/dpc-sdp/bay-cli"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/dpc-sdp/bay-cli/releases/download/v0.1.1/bay-cli_darwin_arm64.tar.gz"
      sha256 "602466d79b3686b7692292c65f00af3977cffc47a48eb693a9bb5bd0fe4d6542"

      def install
        bin.install "bay"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dpc-sdp/bay-cli/releases/download/v0.1.1/bay-cli_darwin_x86_64.tar.gz"
      sha256 "bc8f0e2f4e7fef0eb7686b609c54730d188d5abbb93d1beb196a7b451404362b"

      def install
        bin.install "bay"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dpc-sdp/bay-cli/releases/download/v0.1.1/bay-cli_linux_arm64.tar.gz"
      sha256 "a25fbfa991b77b8bc0e9ad1effd9ff07b82a3b5f1517c5c7ac7eb5318744c9a1"

      def install
        bin.install "bay"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dpc-sdp/bay-cli/releases/download/v0.1.1/bay-cli_linux_x86_64.tar.gz"
      sha256 "84dd0d37af9047467a7a306eb708c5cce9f956c252ed9db8c906db9f241f891c"

      def install
        bin.install "bay"
      end
    end
  end
end
